# Dataset documentation, generated by data-raw/document_datasets.R.
# Do not edit by hand: edit the registry in test_types.R or the generator,
# then re-run that script.

#' Algal growth inhibition (72 h)
#'
#' Simulated example data for the `algal_growth` test type, with a design following OECD 201. Concentrations are in mg/L.
#'
#' @format A data frame with 21 rows and 3 columns:
#' \describe{
#'   \item{conc}{Nominal exposure concentration, in the units given below. Zero is the control.}
#'   \item{replicate}{Replicate identifier within concentration.}
#'   \item{growth_rate}{Response: specific growth rate.}
#' }
#' @source Simulated by `data-raw/generate_datasets.R`. The parameters used
#'   to generate the data are stored in the `truth` attribute of the object,
#'   so that a fitted estimate can be compared against the value that
#'   produced it.
"algal_growth"

#' Daphnid acute immobilisation (48 h)
#'
#' Simulated example data for the `daphnia_immobilisation` test type, with a design following OECD 202. Concentrations are in mg/L.
#'
#' @format A data frame with 28 rows and 5 columns:
#' \describe{
#'   \item{conc}{Nominal exposure concentration, in the units given below. Zero is the control.}
#'   \item{replicate}{Replicate identifier within concentration.}
#'   \item{total}{Number of individuals exposed in the replicate.}
#'   \item{immobile}{Individuals immobilised, as recorded on the bench sheet. The analysis uses its complement, `mobile`, so that the response declines with concentration.}
#'   \item{mobile}{Response: mobile individuals.}
#' }
#' @source Simulated by `data-raw/generate_datasets.R`. The parameters used
#'   to generate the data are stored in the `truth` attribute of the object,
#'   so that a fitted estimate can be compared against the value that
#'   produced it.
"daphnia_immobilisation"

#' Fish early life stage survival (7 d)
#'
#' Simulated example data for the `fish_larval_survival` test type, with a design following OECD 210. Concentrations are in mg/L.
#'
#' @format A data frame with 28 rows and 4 columns:
#' \describe{
#'   \item{conc}{Nominal exposure concentration, in the units given below. Zero is the control.}
#'   \item{replicate}{Replicate identifier within concentration.}
#'   \item{total}{Number of individuals exposed in the replicate.}
#'   \item{alive}{Response: surviving larvae.}
#' }
#' @source Simulated by `data-raw/generate_datasets.R`. The parameters used
#'   to generate the data are stored in the `truth` attribute of the object,
#'   so that a fitted estimate can be compared against the value that
#'   produced it.
"fish_larval_survival"

#' Daphnid reproduction (21 d)
#'
#' Simulated example data for the `daphnia_reproduction` test type, with a design following OECD 211. Concentrations are in mg/L.
#'
#' @format A data frame with 70 rows and 3 columns:
#' \describe{
#'   \item{conc}{Nominal exposure concentration, in the units given below. Zero is the control.}
#'   \item{replicate}{Replicate identifier within concentration.}
#'   \item{offspring}{Response: offspring per surviving adult.}
#' }
#' @source Simulated by `data-raw/generate_datasets.R`. The parameters used
#'   to generate the data are stored in the `truth` attribute of the object,
#'   so that a fitted estimate can be compared against the value that
#'   produced it.
"daphnia_reproduction"

#' Fertilisation success (1 h)
#'
#' Simulated example data for the `fertilisation_success` test type, with a design following ASTM E1563. Concentrations are in ug/L.
#'
#' @format A data frame with 28 rows and 4 columns:
#' \describe{
#'   \item{conc}{Nominal exposure concentration, in the units given below. Zero is the control.}
#'   \item{replicate}{Replicate identifier within concentration.}
#'   \item{total}{Number of individuals exposed in the replicate.}
#'   \item{fertilised}{Response: fertilised ova.}
#' }
#' @source Simulated by `data-raw/generate_datasets.R`. The parameters used
#'   to generate the data are stored in the `truth` attribute of the object,
#'   so that a fitted estimate can be compared against the value that
#'   produced it.
"fertilisation_success"

#' Larval development (48 h)
#'
#' Simulated example data for the `larval_development` test type, with a design following ASTM E724. Concentrations are in ug/L.
#'
#' @format A data frame with 28 rows and 4 columns:
#' \describe{
#'   \item{conc}{Nominal exposure concentration, in the units given below. Zero is the control.}
#'   \item{replicate}{Replicate identifier within concentration.}
#'   \item{total}{Number of individuals exposed in the replicate.}
#'   \item{normal}{Response: proportion normal larvae.}
#' }
#' @source Simulated by `data-raw/generate_datasets.R`. The parameters used
#'   to generate the data are stored in the `truth` attribute of the object,
#'   so that a fitted estimate can be compared against the value that
#'   produced it.
"larval_development"

#' Coral symbiont retention (10 d)
#'
#' Simulated example data for the `coral_bleaching` test type, with a design following no standard guideline. Concentrations are in ug/L.
#'
#' @format A data frame with 35 rows and 3 columns:
#' \describe{
#'   \item{conc}{Nominal exposure concentration, in the units given below. Zero is the control.}
#'   \item{replicate}{Replicate identifier within concentration.}
#'   \item{prop_symbiont}{Response: symbiont density relative to control.}
#' }
#' @source Simulated by `data-raw/generate_datasets.R`. The parameters used
#'   to generate the data are stored in the `truth` attribute of the object,
#'   so that a fitted estimate can be compared against the value that
#'   produced it.
"coral_bleaching"

#' Earthworm acute survival (14 d)
#'
#' Simulated example data for the `earthworm_survival` test type, with a design following OECD 207. Concentrations are in mg/kg dry soil.
#'
#' @format A data frame with 28 rows and 4 columns:
#' \describe{
#'   \item{conc}{Nominal exposure concentration, in the units given below. Zero is the control.}
#'   \item{replicate}{Replicate identifier within concentration.}
#'   \item{total}{Number of individuals exposed in the replicate.}
#'   \item{alive}{Response: surviving adults.}
#' }
#' @source Simulated by `data-raw/generate_datasets.R`. The parameters used
#'   to generate the data are stored in the `truth` attribute of the object,
#'   so that a fitted estimate can be compared against the value that
#'   produced it.
"earthworm_survival"

#' Earthworm reproduction (56 d)
#'
#' Simulated example data for the `earthworm_reproduction` test type, with a design following OECD 222. Concentrations are in mg/kg dry soil.
#'
#' @format A data frame with 28 rows and 3 columns:
#' \describe{
#'   \item{conc}{Nominal exposure concentration, in the units given below. Zero is the control.}
#'   \item{replicate}{Replicate identifier within concentration.}
#'   \item{juveniles}{Response: juveniles per vessel.}
#' }
#' @source Simulated by `data-raw/generate_datasets.R`. The parameters used
#'   to generate the data are stored in the `truth` attribute of the object,
#'   so that a fitted estimate can be compared against the value that
#'   produced it.
"earthworm_reproduction"

#' Seedling emergence (21 d)
#'
#' Simulated example data for the `plant_emergence` test type, with a design following OECD 208. Concentrations are in mg/kg dry soil.
#'
#' @format A data frame with 28 rows and 4 columns:
#' \describe{
#'   \item{conc}{Nominal exposure concentration, in the units given below. Zero is the control.}
#'   \item{replicate}{Replicate identifier within concentration.}
#'   \item{sown}{Number of individuals exposed in the replicate.}
#'   \item{emerged}{Response: emerged seedlings.}
#' }
#' @source Simulated by `data-raw/generate_datasets.R`. The parameters used
#'   to generate the data are stored in the `truth` attribute of the object,
#'   so that a fitted estimate can be compared against the value that
#'   produced it.
"plant_emergence"

#' Seedling shoot biomass (21 d)
#'
#' Simulated example data for the `plant_growth` test type, with a design following OECD 208. Concentrations are in mg/kg dry soil.
#'
#' @format A data frame with 28 rows and 3 columns:
#' \describe{
#'   \item{conc}{Nominal exposure concentration, in the units given below. Zero is the control.}
#'   \item{replicate}{Replicate identifier within concentration.}
#'   \item{dry_weight}{Response: shoot dry weight.}
#' }
#' @source Simulated by `data-raw/generate_datasets.R`. The parameters used
#'   to generate the data are stored in the `truth` attribute of the object,
#'   so that a fitted estimate can be compared against the value that
#'   produced it.
"plant_growth"

#' Sediment amphipod survival (10 d)
#'
#' Simulated example data for the `amphipod_survival` test type, with a design following USEPA 600/R-94/025. Concentrations are in mg/kg dry sediment.
#'
#' @format A data frame with 35 rows and 4 columns:
#' \describe{
#'   \item{conc}{Nominal exposure concentration, in the units given below. Zero is the control.}
#'   \item{replicate}{Replicate identifier within concentration.}
#'   \item{total}{Number of individuals exposed in the replicate.}
#'   \item{alive}{Response: surviving amphipods.}
#' }
#' @source Simulated by `data-raw/generate_datasets.R`. The parameters used
#'   to generate the data are stored in the `truth` attribute of the object,
#'   so that a fitted estimate can be compared against the value that
#'   produced it.
"amphipod_survival"

#' Bacterial bioluminescence inhibition (15 min)
#'
#' Simulated example data for the `bioluminescence_inhibition` test type, with a design following ISO 11348. Concentrations are in mg/L.
#'
#' @format A data frame with 27 rows and 3 columns:
#' \describe{
#'   \item{conc}{Nominal exposure concentration, in the units given below. Zero is the control.}
#'   \item{replicate}{Replicate identifier within concentration.}
#'   \item{rlu}{Response: relative light units.}
#' }
#' @source Simulated by `data-raw/generate_datasets.R`. The parameters used
#'   to generate the data are stored in the `truth` attribute of the object,
#'   so that a fitted estimate can be compared against the value that
#'   produced it.
"bioluminescence_inhibition"

#' Soil nitrogen transformation (28 d)
#'
#' Simulated example data for the `nitrification_inhibition` test type, with a design following OECD 216. Concentrations are in mg/kg dry soil.
#'
#' @format A data frame with 28 rows and 3 columns:
#' \describe{
#'   \item{conc}{Nominal exposure concentration, in the units given below. Zero is the control.}
#'   \item{replicate}{Replicate identifier within concentration.}
#'   \item{nitrate_rate}{Response: nitrate formation rate.}
#' }
#' @source Simulated by `data-raw/generate_datasets.R`. The parameters used
#'   to generate the data are stored in the `truth` attribute of the object,
#'   so that a fitted estimate can be compared against the value that
#'   produced it.
"nitrification_inhibition"

